site_name: Fontlab Design Assets
site_description: Design assets by Fontlab Ltd.
site_author: Fontlab Ltd.
site_url: https://fontlabcom.github.io/fontlab-design-assets/

repo_name: fontlabcom/fontlab-design-assets
repo_url: https://github.com/fontlabcom/fontlab-design-assets
edit_uri: edit/main/src_docs/md/

docs_dir: md
site_dir: ../docs

theme:
  name: materialx
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

nav:
  - Home: index.md
  - Assets: assets.md
  - About: about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fontlabcom
    - icon: fontawesome/solid/globe
      link: https://www.fontlab.com/
